- src/abcui.js
Fix to the `assetsPath` conditional.
> Fix to the `assetsPath` conditional.

- src/common/actions/PreviousUsersActions.js
This makes my testing life a bit easier.
> User fallback

- src/native/components/ChangePasswordAppComponent.js
- src/native/components/ChangePinAppComponent.js
- src/native/components/LogInAppComponent.js
- src/native/components/screens/LoginUsernamePasswordScreenComponent.js
Attempt on adding accessibility for iOS edge.app
> Added accessibility

- src/native/styles/screens/NewAccountReviewScreenStyle.js
Also put some paddings for readability.
> Fix wrapping of the account information screen info

- src/common/styles/adSpecific/PasswordStatusStyle.js
- src/native/components/abSpecific/FourDigitInputComponent.js
- src/native/components/abSpecific/PasswordStatusComponent.js
- src/native/connectors/abSpecific/CreateFourDigitPinConnector.js
• Also fixed style issue on Change Password and New Password screens
fixes : https://app.asana.com/0/361770107085503/504146355149007
fixes : https://app.asana.com/0/361770107085503/539038301050902
> Adjusted the 4dot component to be able to not auto-repeat focus.

- packages/edge-login-ui-rn/src/common/reducers/WorkflowReducer.js
- packages/edge-login-ui-rn/src/native/components/screens/existingAccout/LoginWithRecoveryQuestionsScreenComponent.js
- packages/edge-login-ui-rn/src/native/connectors/componentConnectors/HeaderRecoverPasswordLogin.js
- packages/edge-login-ui-rn/src/native/styles/screens/LoginWithRecoveryStyles.js
https://app.asana.com/0/361770107085503/570044384672901
> Added SafeAreaView on Login Recovery Password Screen, remove steps on it's header.

- packages/edge-login-ui-rn/src/native/connectors/LogInAppConnector.js
This fixed a bug I noticed where the pin screen would not auto load anymore.
> fixed regression not going to pin screen.

- packages/edge-login-ui-rn/src/native/components/screens/newAccount/TermsAndConditionsScreenComponent.js
- packages/edge-login-ui-rn/src/native/styles/screens/OtpErrorScreenStyle.js
https://app.asana.com/0/361770107085503/585458825515910
> Change header to fix displays

- packages/edge-login-ui-react/package.json
- packages/edge-login-ui-react/sass-loader.js
- packages/edge-login-ui-web/package.json
We still need to find a Windows box to verify these changes, but they should solve our problems based on code inspection.
> Windows Fixes

- packages/edge-login-ui-react/src/lib/rootReducer.js
- packages/edge-login-ui-react/src/modules/AccountManagement/ChangePassword/ChangePassword.js
- packages/edge-login-ui-react/src/modules/AccountManagement/PasswordRecovery/PasswordRecovery.middleware.js
- packages/edge-login-ui-react/src/modules/AccountManagement/PasswordRecoveryToken/PasswordRecoveryToken.webStyle.scss
- packages/edge-login-ui-react/src/modules/Modals/ForgotPassword/ForgotPassword.mobile.js
- packages/edge-login-ui-react/src/modules/Modals/ForgotPassword/ForgotPassword.web.js
- packages/edge-login-ui-react/src/modules/Modals/Success/Success.action.js
- packages/edge-login-ui-react/src/modules/Modals/Success/Success.js
- packages/edge-login-ui-react/src/modules/Modals/Success/Success.mobileStyle.scss
- packages/edge-login-ui-react/src/modules/Modals/Success/Success.reducer.js
- packages/edge-login-ui-react/src/modules/Modals/Success/Success.webStyle.scss
- packages/edge-login-ui-react/src/modules/Signup/Username/Username.middleware.js
- packages/edge-login-ui-react/src/theme/globals.scss
- Added error handling on account management password, added screens when edge login is used
- Change some Airbitz string to Edge, Added username error handling
- Added warning message when changing password successfully 
- Fix sumbission bug on Password Recovery when not selecting a question
- Fix firefox bugs and enhancement on forms and styling
> ui-react: Bug fixes and enhancement.

- packages/edge-login-ui-rn/src/common/actions/LoginAction.js
- packages/edge-login-ui-rn/src/common/constants/ErrorConstants.js
- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/util/ErrorMessageUtil.js
- packages/edge-login-ui-rn/src/common/util/index.js
This fixes the unhandled syntax error bug. It also creates a utility for translating programmer bugs to user friendly bugs when necessary.
> Fixed misc bug during 2fa

- packages/edge-login-ui-rn/src/common/locales/en_US.js
Asana Task https://app.asana.com/0/361770107085503/693269684549043
> Fix recovery text from login screen

- packages/edge-login-ui-rn/src/native/components/common/Header.js
fixes Asana https://app.asana.com/0/361770107085503/775354251612216
> Have header back button be Back instead of BACK

- packages/edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPasswordScreenComponent.js
- packages/edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPinScreenComponent.js
The purpose of this task is to change the uppercase 'DONE' button titles to 'Done'.
Asana Task: https://app.asana.com/0/361770107085503/781564217904944/f
> Change 'DONE' to 'Done' on buttons

- packages/edge-login-ui-react/src/hackWindow.js
- packages/edge-login-ui-react/src/modules/Login/Login.middleware.js
- packages/edge-login-ui-react/src/modules/Signup/Signup.middleware.js
This would be needed for the web to handle 2FA, among other things.
> react: Actually implement `accountOptions`

- packages/edge-login-ui-web/README.md
This is the way Augur is using our stuff.
> web: Update the readme file

- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountPasswordScreenComponent.js
The purpose of this task is to enforce proper capitalization (in my opinion) of button titles, scene titles, and other strings within the login system.
Currently there is no official Asana task related to this PR.
> Adjustments to strings for proper capitalization

- packages/edge-login-ui-react/src/demo/index.js
- packages/edge-login-ui-react/src/modules/Login/CachedUsers/CachedUsers.middleware.js
@kylanhurt This should fix the bug you found.
> react: Fix removing usernames from the device

- packages/edge-login-ui-rn/src/native/components/common/DropDownList.js
Change keyExtractor to return index.toString()
> Fix React error that key is not a string

- packages/edge-login-ui-rn/src/common/styles/adSpecific/PasswordStatusStyle.js
- packages/edge-login-ui-rn/src/common/styles/common/ButtonStyles.js
- packages/edge-login-ui-rn/src/common/styles/common/FormFieldStyle.js
- packages/edge-login-ui-rn/src/native/components/abSpecific/LogoImageHeader.js
- packages/edge-login-ui-rn/src/native/components/screens/newAccount/TermsAndConditionsScreenComponent.js
- packages/edge-login-ui-rn/src/native/styles/components/FourDotInputStyle.js
- packages/edge-login-ui-rn/src/native/styles/components/LogoHeaderStyle.js
- packages/edge-login-ui-rn/src/native/styles/index.js
- packages/edge-login-ui-rn/src/native/styles/screens/LandingScreenStyle.js
- packages/edge-login-ui-rn/src/native/styles/screens/LoginPasswordScreenStyle.js
- packages/edge-login-ui-rn/src/native/styles/screens/PinLoginScreenStyle.js
- packages/edge-login-ui-rn/src/native/styles/screens/TermsAndConditionsScreenStyle.js
The purpose of this task is to make more of the login area scale with respect to the size of the device.
Asana Task: https://app.asana.com/0/361770107085503/811109991964543/f
> Make More Adjustments to Login Scaling

- packages/edge-login-ui-rn/src/common/styles/adSpecific/PasswordStatusStyle.js
- packages/edge-login-ui-rn/src/common/styles/common/ButtonStyles.js
- packages/edge-login-ui-rn/src/native/components/abSpecific/PasswordStatusComponent.js
- packages/edge-login-ui-rn/src/native/components/screens/existingAccout/RecoverPasswordScreenComponent.js
- packages/edge-login-ui-rn/src/native/styles/screens/NewAccountPasswordScreenStyle.js
- packages/edge-login-ui-web/src/demo/components/Page.js
The purpose of this task is to fix the overlap of the password cracking syntax and password criteria. Also, to fix the height of the password recovery email modal button.
Asana Task: https://app.asana.com/0/361770107085503/855190199253029/f
Asana Task: https://app.asana.com/0/361770107085503/852461267151391/f
> Fix Some Password & Recovery Styling

- packages/edge-login-ui-rn/src/native/styles/screens/SetAccountPinScreenStyle.js
The purpose of this task is to adjust the create new account PIN scene, specifically to allow more room for the error feedback (red text).
Asana Task: https://app.asana.com/0/361770107085503/870219205137174/f
> Fix issues with createAccount PIN scene

- packages/edge-login-ui-rn/src/native/styles/screens/NewAccountUsernameScreenStyle.js
The purpose of this task is to allow the create username instructions to wrap rather than have the text get cut off (specifically in Spanish).
Asana Task: https://app.asana.com/0/361770107085503/875186582391425/f
> Allow new username instructions to wrap

- packages/edge-login-ui-rn/src/native/styles/screens/NewAccountReviewScreenStyle.js
- Spanish - Create account - Review Account: The " ! "strikes through the word "informacion"
> Fix warning box paddings and height

- packages/edge-login-ui-web/src/frame/root-api.js
This reverts commit ffa6ce17b5b4c9f5b45f5e2a41e454c4225a774f.
> Revert "web: Stop using JSON for bridge data"

- packages/edge-login-ui-rn/src/native/components/screens/existingAccout/OtpErrorScreenComponent.js
https://app.asana.com/0/361770107085503/881414690448659/f
> Wrap 2FA scene in SafeAreaView to account for notch on iPhone X

- packages/edge-login-ui-rn/src/common/styles/common/HeaderStyles.js
- packages/edge-login-ui-rn/src/native/components/common/Header.js
- packages/edge-login-ui-rn/src/native/styles/screens/ConfirmPasswordRecoverySceneStyles.js
- packages/edge-login-ui-rn/src/native/styles/screens/LoginWithRecoveryStyles.js
- packages/edge-login-ui-rn/src/native/styles/screens/OtpErrorScreenStyle.js
- packages/edge-login-ui-rn/src/native/styles/screens/RecoverPasswordSceneStyles.js
Only render subtitle text if there is a subtitle
https://app.asana.com/0/361770107085503/907331382441035/f
> Adjust header styles

- packages/edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent.js
- packages/edge-login-ui-rn/src/native/styles/screens/PinLoginScreenStyle.js
Task: PIN login: close username popup
> Pin Login Screen: close username dropdown when clicked outside

- package.json
- packages/edge-login-ui-rn/src/common/actions/LoginAction.js
- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
FIxes Asana 2FA - "Unexpected end of data"
https://app.asana.com/0/361770107085503/911495125197671
Also put back precommit script. not sure why removed but an essential part of my process.
> fix error message with OTP error

- packages/edge-login-ui-rn/src/common/constants/IconConstants.js
Task: https://app.asana.com/0/361770107085503/949209169442513
> Remove outline icons of Ionicons

- packages/edge-login-ui-react/src/modules/Modals/AccountCacheDelete/AccountCacheDelete.mobile.js
task: edge-login-ui-web - Unable to delete account
> Fix bug on delete cached mobile modal

- packages/edge-login-ui-react/src/locales/default.js
- packages/edge-login-ui-react/src/modules/AccountManagement/AccountManagement.mobile.js
- packages/edge-login-ui-react/src/modules/AccountManagement/AccountManagement.web.js
- packages/edge-login-ui-react/src/modules/AccountManagement/PasswordRecoveryToken/PasswordRecoveryToken.middleware.js
- packages/edge-login-ui-react/src/modules/Layout/Footer/Footer.mobile.js
- packages/edge-login-ui-react/src/modules/Layout/Footer/Footer.web.js
- packages/edge-login-ui-react/src/modules/Modals/ForgotPassword/ForgotPassword.mobile.js
- packages/edge-login-ui-react/src/modules/Modals/ForgotPassword/ForgotPassword.web.js
Task: edge-login-UI-web: wrong url to app
> Change url links to latest url app

- packages/edge-login-ui-rn/src/native/components/screens/newAccount/SetAccountPinScreenComponent.js
Task: Network error popup on account creation
> Fix network error popup on account creation

- packages/edge-login-ui-rn/src/common/constants/Theme.js
The purpose of this task is to adjust the header to handle upgrading RN59 and RNRF.
Asana Task: https://app.asana.com/0/361770107085503/1122906197217279/f
> Adjust header sizing for RN59

- packages/edge-login-ui-rn/src/common/constants/Theme.js
- packages/edge-login-ui-rn/src/common/styles/common/HeaderStyles.js
- packages/edge-login-ui-rn/src/native/components/common/Header.js
- packages/edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountWelcomeScreenComponent.js
Asana Task: https://app.asana.com/0/361770107085503/1124069358646621/f
> Fix Headers

- packages/edge-login-ui-rn/package.json
- packages/edge-login-ui-rn/src/native/components/abSpecific/EdgeLoginQrComponent.js
This has been tested both on iOS and Android
Asana Task: https://app.asana.com/0/361770107085503/1124218505726214/f
> Fix glitchy QR code issue on 2FA scene

- packages/edge-login-ui-rn/package.json
- packages/edge-login-ui-rn/src/common/util/ModalManager.js
- packages/edge-login-ui-rn/src/native/components/common/FullScreenModal.js
- packages/edge-login-ui-rn/src/native/components/common/Modal.js
- packages/edge-login-ui-rn/src/native/components/common/StaticModal.js
- yarn.lock
This is pretty gross, but it gets the job done?
> Fix the modals to cover the screen

- packages/edge-login-ui-rn/src/native/components/abSpecific/FourDigitInputComponent.js
Focusing caused us to focus, which caused us to focus, which...
> Fix infinite keyboard flutter in change PIN

- packages/edge-login-ui-rn/src/native/components/abSpecific/PinKeypad.js
- packages/edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent.js
- packages/edge-login-ui-rn/src/native/styles/components/PinKeypadStyle.js
- packages/edge-login-ui-rn/src/native/styles/screens/PinLoginScreenStyle.js
Login UI - iPad buttons are too wide
Login UI - The space on the 6th username is not tappable to initiate PIN or Fingerprint
> Refactor Login UI bugs and features

- packages/edge-login-ui-rn/src/common/actions/LoginAction.js
- packages/edge-login-ui-rn/src/common/constants/index.js
- packages/edge-login-ui-rn/src/common/reducers/LoginReducer.js
- packages/edge-login-ui-rn/src/common/reducers/WorkflowReducer.js
- packages/edge-login-ui-rn/src/types/ReduxTypes.js
task: Password recovery should proceed to 2FA if enabled on account
> Password Recovery proceed to 2FA if enabled on account

- packages/edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPasswordScreenComponent.js
- packages/edge-login-ui-rn/src/native/components/screens/existingAccout/ChangeAccountPinScreenComponent.js
Task: https://app.asana.com/0/361770107085503/1137874285317658
> Added SafeAreaView for Change Pin and Password Screen

- packages/edge-login-ui-rn/src/native/components/LogInAppComponent.js
- packages/edge-login-ui-rn/src/native/components/abSpecific/LogoImageHeader.js
- packages/edge-login-ui-rn/src/native/components/exportAPIComponents/LoginScreen.js
- packages/edge-login-ui-rn/src/native/components/screens/LandingScreenComponent.js
- packages/edge-login-ui-rn/src/native/components/screens/LoginUsernamePasswordScreenComponent.js
- packages/edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent.js
Task: Send Logs from Login screen tap logo 5 times like Airbitz (https://app.asana.com/0/361770107085503/1135306975343601)
Note: Approve https://github.com/EdgeApp/edge-react-gui/pull/1667 for this to be functional
> Pressing the primary logo 5x will trigger a callback

- packages/edge-login-ui-react/src/components/LoginWithPassword.js
- packages/edge-login-ui-react/src/locales/default.js
- packages/edge-login-ui-react/src/styles/GlobalButtons.scss
- packages/edge-login-ui-react/src/styles/LoginWithPassword.scss
Task: Edge Login - Switch "Login with Edge" and Right Arrow Icon for logging in via Password. Make the - 
https://app.asana.com/0/361770107085503/1146052235553327
> Change Web Ui Design on Login Password Screen

- packages/edge-login-ui-react/src/styles/GlobalInputs.scss
Note: The enter pin label will be labeled not only on the pin screen. But also sign up screen and change pin screen.
> Web Ui - Center Enter Pin label on pin form component

- packages/edge-login-ui-rn/src/common/actions/CreateAccountActions.js
- packages/edge-login-ui-rn/src/common/actions/LoginAction.js
- packages/edge-login-ui-rn/src/common/actions/PreviousUsersActions.js
Task: Username List Login - Top 3 most recent used and alphabetical order after - https://app.asana.com/0/361770107085503/1155828395051751
Replace lastuser.JSON file to lastusers.JSON  file for storing last login users. User List make 3 most recent login users top, and sort the rest in alphabetical order
> Username List Login - Top 3 most recent used and alphabetical order after

- packages/edge-login-ui-rn/src/common/actions/PreviousUsersActions.js
- packages/edge-login-ui-rn/src/common/reducers/LoginReducer.js
- packages/edge-login-ui-rn/src/common/reducers/PreviousUsersReducer.js
- packages/edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent.js
- packages/edge-login-ui-rn/src/native/connectors/screens/PinLoginScreenConnector.js
- packages/edge-login-ui-rn/src/types/ReduxTypes.js
Also, use Flow types more generously.
> rn: Rewrite `getPreviousUsers` to not crash

- README.md
> Fix "develop" repo links to "master"

- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
Task: Create Account - Account Confirmation - 4th Agreement - Remove the period - https://app.asana.com/0/361770107085503/1161050394481993
> Remove period on the 4th term in the term condition screen

- packages/edge-login-ui-rn/src/native/styles/screens/RecoverPasswordSceneStyles.js
Task: Password recovery questions list doesn't fill the screen - https://app.asana.com/0/361770107085503/1126866685130798
NOTE: Merge with https://github.com/EdgeApp/edge-react-gui/pull/1877
> Password Recovery Scene Question List Full Height

- packages/edge-login-ui-rn/package.json
- packages/edge-login-ui-rn/src/actions/LoginCompleteActions.js
- packages/edge-login-ui-rn/src/components/publicApi/LoginScreen.js
- packages/edge-login-ui-rn/src/components/themed/ThemedModal.js
- yarn.lock
This ensures that no modals will be left open once we complete the login process.
> rn: Use the new Airship features

- packages/edge-login-ui-rn/src/components/screens/existingAccout/SecurityAlertsScreen.js
If something goes wrong talking to the server, we don't want to lock users out of their account.
> Add a skip button to the security alert screen

- packages/edge-login-ui-rn/src/util/isIphoneX.js
Fixes the appropriate safe area spacings on the newer iPhone 12 devices
> Refactor and add new iPhone 12 devices for the isIPhoneX function

- packages/edge-login-ui-rn/src/actions/LoginAction.js
- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
- packages/edge-login-ui-rn/src/components/common/AlertDropdown.js
- packages/edge-login-ui-rn/src/components/services/AirshipInstance.js
- packages/edge-login-ui-rn/src/constants/themes/edgeDark.js
- packages/edge-login-ui-rn/src/types/Theme.js
> Added Error Dropdown Toast and implement it on Password Recovery Modal

- packages/edge-login-ui-rn/src/components/screens/PasswordLoginScreen.js
This will make life much more pleasant for everyone with multiple devices. This new UI isn't themed, because the rest of the scene isn't themed either.
> rn: Expose the QR modal from the password login screen

- packages/edge-login-ui-rn/src/components/screens/existingAccout/SecurityAlertsScreen.js
This makes use of more common components.
> rn: Improve security alerts screen appearance

- packages/edge-login-ui-rn/package.json
- packages/edge-login-ui-rn/src/actions/LoginAction.js
- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
- packages/edge-login-ui-rn/src/components/modals/QrCodeModal.js
- packages/edge-login-ui-rn/src/components/publicApi/PublicLoginScreen.js
- yarn.lock
This requires https://github.com/EdgeApp/edge-core-js/pull/355 for the Flow types to work, so please don't merge until that is published.
> Show a spinner in the barcode login modal

- packages/edge-login-ui-rn/android/src/main/java/co/airbitz/AbcCoreJsUi/AbcCoreJsUiModule.java
- packages/edge-login-ui-rn/ios/AbcCoreJsUi.m
- packages/edge-login-ui-rn/package.json
- packages/edge-login-ui-rn/src/actions/LoginInitActions.js
- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
- packages/edge-login-ui-rn/src/components/modals/PermissionsAlertModal.js
- packages/edge-login-ui-rn/src/components/publicApi/PublicLoginScreen.js
- packages/edge-login-ui-rn/src/components/themed/ThemedButtons.js
- packages/edge-login-ui-rn/src/constants/themes/edgeDark.js
- packages/edge-login-ui-rn/src/types/ReduxTypes.js
- packages/edge-login-ui-rn/src/types/Theme.js
- yarn.lock
Note: Merge https://github.com/EdgeApp/edge-react-gui/pull/2500 after this one
> Notification and ios Background Refresh checks

- packages/edge-login-ui-rn/src/constants/themes/edgeDark.js
Merged along with https://github.com/EdgeApp/edge-react-gui/pull/2531
> Change modal color as per new design

- packages/edge-login-ui-rn/src/components/modals/ButtonsModal.js
- packages/edge-login-ui-rn/src/components/screens/existingAccout/ChangeRecoveryScreen.js
Since I can't stop this from crashing, we should remove it for now.
> rn: Disable the reovery email modal on Android

- flow-typed/react-native-material-textfield.js
- packages/edge-login-ui-rn/src/components/abSpecific/AccountInfoComponent.js
- packages/edge-login-ui-rn/src/components/abSpecific/FourDigitInputComponent.js
- packages/edge-login-ui-rn/src/components/common/Checkbox.js
- packages/edge-login-ui-rn/src/components/common/FormField.js
- packages/edge-login-ui-rn/src/components/common/MaterialInput.js
- packages/edge-login-ui-rn/src/components/common/TextAndIconButton.js
- packages/edge-login-ui-rn/src/components/screens/LandingScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPasswordScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPinScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountReviewScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountUsernameScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountWelcomeScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/TermsAndConditionsScreen.js
It should be pretty self explanatory. Let me know what kind of information you would like for these PRs that add test IDs. They will be pretty common and hopefully we can streamline their integration into the code as much as possible. We will be waiting to merge the tests that depend on them until these IDs are available in master to avoid having failing tests from IDs.
> Test IDs added and working for Create Account Flow

- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountWelcomeScreen.js
- packages/edge-login-ui-rn/src/components/themed/SimpleSceneHeader.js
> Bring back the ability to return to the landing screen from registration flow

- packages/edge-login-ui-rn/README.md
- packages/edge-login-ui-rn/src/components/navigation/Router.js
- packages/edge-login-ui-rn/src/components/publicApi/LoginUiProvider.js
- packages/edge-login-ui-rn/src/index.js
- Add a `LoginUiProvider` component to fix Airship layout bugs.
This requires a type-safe solution for using React hooks. I personally prefer #288 - Typescript support, but we could also grab the Flow hacks from the GUI instead.
> Add a `LoginUiProvider` component

- packages/edge-login-ui-rn/package.json
- packages/edge-login-ui-rn/src/actions/CreateAccountActions.js
- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountUsernameScreen.js
- packages/edge-login-ui-rn/src/components/themed/EdgeTextFieldOutlined.js
- packages/edge-login-ui-rn/src/components/themed/FormError.js
- packages/edge-login-ui-rn/src/components/themed/ThemedButtons.js
- packages/edge-login-ui-rn/src/constants/themes/edgeDark.js
- packages/edge-login-ui-rn/src/constants/workflows.js
- packages/edge-login-ui-rn/src/types/Theme.js
- packages/edge-login-ui-rn/src/util/hooks.js
- yarn.lock
> UI2 Create Account choose username

- .github/workflows/pr-checks.yml
- .github/workflows/pr-rebase.yml
Added
- GitHub Workflow using block-wip-pr-action
- GitHub Workflow using rebase/autosquash
> Added gitflow scripts

- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPasswordScreen.js
- packages/edge-login-ui-rn/src/components/services/ReduxStore.js
- packages/edge-login-ui-rn/src/components/themed/EdgeTextFieldOutlined.js
- packages/edge-login-ui-rn/src/components/themed/Fade.js
- packages/edge-login-ui-rn/src/components/themed/IconSignal.js
- packages/edge-login-ui-rn/src/components/themed/PasswordStatus.js
- packages/edge-login-ui-rn/src/constants/themes/edgeDark.js
- packages/edge-login-ui-rn/src/constants/workflows.js
- packages/edge-login-ui-rn/src/types/Theme.js
> UI2 create account set password

- packages/edge-login-ui-rn/src/common/locales/en_US.js
- packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPinScreen.js
- packages/edge-login-ui-rn/src/components/themed/DigitInput.js
- packages/edge-login-ui-rn/src/components/themed/FormError.js
- packages/edge-login-ui-rn/src/components/themed/PinDots.js
- packages/edge-login-ui-rn/src/constants/workflows.js
> UI2 create account set up pin

- packages/edge-login-ui-rn/src/components/screens/newAccount/TermsAndConditionsScreen.js
- packages/edge-login-ui-rn/src/components/themed/Checkbox.js
- packages/edge-login-ui-rn/src/components/themed/EdgeText.js
- packages/edge-login-ui-rn/src/constants/workflows.js
> UI2 Account Confirmation terms screen

- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPasswordScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPinScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountReviewScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountUsernameScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountWelcomeScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/TermsAndConditionsScreen.js
- packages/edge-login-ui-rn/src/components/themed/Divider.js
- packages/edge-login-ui-rn/src/components/themed/SimpleSceneHeader.js
If you have made **any** visual changes to the GUI. Make sure you have:
> Fix spacing on Create Account scene

- packages/edge-login-ui-rn/src/components/themed/EdgeTextFieldOutlined.js
> Change small outlined field padding and font size

- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPasswordScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPinScreen.js
- packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountUsernameScreen.js
- packages/edge-login-ui-rn/src/components/themed/BackButton.js
> Backspace / Exit buttons to previous page - Account Setup

- packages/edge-login-ui-rn/src/actions/CreateAccountActions.js
- packages/edge-login-ui-rn/src/actions/WorkflowActions.js
- packages/edge-login-ui-rn/src/components/modals/QrCodeModal.js
If QA finds any bugs where modals stay suck open, we could consider merging this branch as a solution.
> rn: Always close modals on the way out the door

- packages/edge-login-ui-rn/src/components/modals/QrCodeModal.js
- packages/edge-login-ui-rn/src/components/screens/OtpErrorScreen.js
- packages/edge-login-ui-rn/src/components/screens/PasswordLoginScreen.js
- packages/edge-login-ui-rn/src/components/screens/existingAccout/OtpRepairScreen.js
- Prevent a crash when opening the QR-login modal.
> rn: Fix the crash in the QR-login modal

- packages/edge-login-ui-rn/src/actions/WorkflowActions.js
- packages/edge-login-ui-rn/src/components/publicApi/PublicChangePasswordScreen.js
- packages/edge-login-ui-rn/src/components/publicApi/PublicChangePinScreen.js
- packages/edge-login-ui-rn/src/components/publicApi/PublicChangeRecoveryScreen.js
- packages/edge-login-ui-rn/src/components/publicApi/PublicOtpRepairScreen.js
- packages/edge-login-ui-rn/src/components/publicApi/PublicSecurityAlertsScreen.js
- packages/edge-login-ui-rn/src/hooks/useClearOnUnmount.js
- rn: Close all modals on scene exit (including auto logout).
> rn: Use hooks to clear the `Airship` on scene exit

- packages/edge-login-ui-rn/src/components/publicApi/PublicLoginScreen.tsx
This doesn't fix anything in particular, other than being consistent with the other public screens.
> rn: Use hooks for the public login screen

- packages/edge-login-ui-rn/src/components/themed/AccountInfo.tsx
- packages/edge-login-ui-rn/src/components/themed/EdgeText.tsx
If you have made **any** visual changes to the GUI. Make sure you have:
*iPhone 8*
*Nexus 4*
> Inconsistent text

- packages/edge-login-ui-rn/src/components/abSpecific/FourDigitInputComponent.tsx
This brings back the keyboard.
> Fix the change PIN input component to be tappable

- packages/edge-login-ui-rn/package.json
- packages/edge-login-ui-rn/src/components/scenes/existingAccout/SecurityAlertsScene.tsx
- packages/edge-login-ui-rn/src/util/utils.ts
- yarn.lock
> Date fns on alert screen date formats

- packages/edge-login-ui-rn/src/components/common/HeaderParentButtons.tsx
---
- https://app.asana.com/0/0/1200838389535079
> Login scene header button empty gap fix

- packages/edge-login-ui-rn/src/components/scenes/newAccount/NewAccountPasswordScene.tsx
- packages/edge-login-ui-rn/src/components/themed/PasswordStatus.tsx
---
- https://app.asana.com/0/0/1201746514637593
> Fix inconsistent text alignment in the password correctness box

- packages/edge-login-ui-rn/src/components/themed/EdgeTextFieldOutlined.tsx
https://user-images.githubusercontent.com/17136567/156232763-0901b3eb-3507-4d60-8db7-861203bc0931.mp4
---
- https://app.asana.com/0/0/1200708773561498
> Show/Hide password text on EdgeTextFieldOutlined Component

- packages/edge-login-ui-rn/src/components/themed/PinButton.tsx
Prevents button outline from bleeding into other buttons on iPhone 13 mini
---
- https://app.asana.com/0/0/1202214724004390
> Fix PIN button width

- packages/edge-login-ui-rn/src/components/scenes/ChangePasswordScene.tsx
- packages/edge-login-ui-rn/src/components/themed/OutlinedTextInput.tsx
Synchronizes the password visibility for multiple input fields.
---
- https://app.asana.com/0/0/1202182151663951
> Sync password eyes
