packages/edge-login-ui-rn/src/common/actions/CreateAccountActions.js
packages/edge-login-ui-rn/src/native/components/exportAPIComponents/PasswordRecoveryScreen.js
packages/edge-login-ui-rn/src/native/components/screens/LandingScreenComponent.js
packages/edge-login-ui-rn/src/native/components/screens/newAccount/CreatingAccountWaitScreenComponent.js
packages/edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountPasswordScreenComponent.js
packages/edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountReviewScreenComponent.js
packages/edge-login-ui-rn/src/native/components/screens/newAccount/SetAccountPinScreenComponent.js
packages/edge-login-ui-rn/src/native/components/screens/newAccount/TermsAndConditionsScreenComponent.js
packages/edge-login-ui-rn/src/native/connectors/screens/newAccount/NewAccountWelcomeScreenConnector.js

This only does anything if `global.firebase` exists which is what edge-react-gui will assign prior to calling into the login-ui

Add firebase event logging

---

packages/edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountReviewScreenComponent.js
packages/edge-login-ui-rn/src/native/components/screens/newAccount/NewAccountUsernameScreenComponent.js
packages/edge-login-ui-rn/src/native/components/screens/newAccount/SetAccountPinScreenComponent.js

The purpose of this task is to change the 'Done' button to 'Next' for account creation since there is still a Terms of Service scene / page next.
Asana Task: https://app.asana.com/0/361770107085503/588399275369074/f

Slight adjustments to 'Next' buttons in Create Account

---

packages/edge-login-ui-rn/src/common/actions/LoginAction.js
packages/edge-login-ui-rn/src/common/reducers/LoginReducer.js
packages/edge-login-ui-rn/src/native/components/abSpecific/FourDigitInputComponent.js

• cleared error and wait if new user is chosen
• kept error message consistent- got rid of null
This pr fixes the following Asana tasks 
PIN Rate Limit warning - Shows "Null" sometimes
https://app.asana.com/0/361770107085503/804314862254080
PIN Rate Limit warning - While locked, cannot log into other accounts from the dropdown - will show same timer
https://app.asana.com/0/361770107085503/804314862254081
PIN Rate Limit warning - The timer freezes during countdown if you exit PIN Login and go into the PIN Login again
https://app.asana.com/0/361770107085503/804314862254082

Moved Rate limit countdown from component to actions

---

packages/edge-login-ui-rn/src/common/locales/en_US.js
packages/edge-login-ui-rn/src/common/locales/strings/enUS.json
packages/edge-login-ui-rn/src/common/util/checkingForOTP.js
packages/edge-login-ui-rn/src/native/components/exportAPIComponents/LoginScreen.js

This moves checking for 2FA reset to login system and throws a system alert if any accounts on the phone have received a 2FA reset request from another device.

check for OTP reset on all account on phone

---

packages/edge-login-ui-rn/src/native/components/common/ImageButton.js
packages/edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent.js
packages/edge-login-ui-rn/src/native/connectors/screens/PinLoginScreenConnector.js
packages/edge-login-ui-rn/src/native/styles/screens/LoginPasswordScreenStyle.js
packages/edge-login-ui-rn/src/native/styles/screens/PinLoginScreenStyle.js

The purpose of this task is to disable touchID once the account has logged in to prevent touchID modal pop up once the app has been entered (logged in).
Asana Task: https://app.asana.com/0/361770107085503/476385730387081/f

Disable touchID button during / after logging in

---

packages/edge-login-ui-rn/android/build.gradle
packages/edge-login-ui-rn/android/gradle/wrapper/gradle-wrapper.properties
packages/edge-login-ui-rn/android/src/main/java/co/airbitz/AbcCoreJsUi/AbcCoreJsUiModule.java
yarn.lock

Upgrade library to 2.0.0.
Make necessary Java code changes to fix breaking API due to new RxJava2 that's now used.
Bump gradle versions
Upload new lock file from new yarn version

URGENT: Fix crashes on Android 8 due to Whorlwind library

---

packages/edge-login-ui-rn/android/src/main/java/co/airbitz/AbcCoreJsUi/AbcCoreJsUiModule.java
packages/edge-login-ui-rn/src/native/keychain.js

Allows bitcoin plugin to work with Bitpay payments. Default RN fetch() uses okhttp which adds a 'utf8' at the end of Content-Type which Bitpay barfs on.

URGENT: Add special hacked androidFetch which does not use okhttp

---

packages/edge-login-ui-rn/src/native/styles/screens/SetAccountPinScreenStyle.js

Adjust height of PIN field on create account slightly to avoid cutting off text on Android

Adjust height of PIN field on create account slightly

---

packages/edge-login-ui-rn/src/common/styles/common/HeaderStyles.js

Slight font size adjustment to prevent the CANCEL text from cutting off behind the title of the screen

Adjust font size of the CANCEL button on the Password Recovery screen

---

packages/edge-login-ui-rn/src/native/connectors/abSpecific/FourDigitInputConnector.js

error was showing up if wait was undefined.. now will only add if a number and > 0
Asana Task. 
Only lock the user out on `PasswordError` events
https://app.asana.com/0/361770107085503/873374534993723

fix error message to only show wait when needed

---

packages/edge-login-ui-web/src/demo/index.html

Add width and scale to <meta> tag

Fix scaling on mobile Safari.

---

packages/edge-login-ui-rn/src/native/components/abSpecific/FourDigitInputComponent.js

Ref callback of TextInput will get NULL if component is unmounted. Do not call this.inputRef.focus() if unmounted.

Track if TextInput is mounted before calling focus()

---

packages/edge-login-ui-react/src/modules/Login/LoginWithPin/LoginWithPin.js
packages/edge-login-ui-react/src/modules/Login/LoginWithPin/LoginWithPin.mobile.js
packages/edge-login-ui-react/src/modules/Login/LoginWithPin/LoginWithPin.web.js

Task:Edge Login - Nothing happens after scanning the QR Code to login
Back then the mounting of QR code is directly attached to the QR code component. The code below is responsible to cancelRequest the QR code polling when user go to the Login W/ PIN screen. Now that the whole Login screen is mounting the qr code polling. The cancelRequest on Login with pin needs to be remove because Login w/ pin is part of the Login component.

Fix some typo, remove code that removes polling on pin login screen.

---

packages/edge-login-ui-rn/src/native/components/abSpecific/PinKeypad.js
packages/edge-login-ui-rn/src/native/components/screens/PinLogInScreenComponent.js
packages/edge-login-ui-rn/src/native/styles/components/PinKeypadStyle.js

Task:
Login UI - FaceID should NOT automatically launch when app is opened
Login UI - If PIN is DISABLED, the number pad is still shown
Login UI - Number pad keyboard Back/Delete button shrink down 20%
Login UI - Prevent PIN number buttons from being highlighted
Login UI - After logging out, the Num Pad is not aligned for the number column 2, 5, 8, 0
Login UI - iPhone X needs a blank space at bottom of Num Pad - Render only in safe view area. Move num pad above to safe view area.

Refactor Login UI bugs and features

---

packages/edge-login-ui-rn/src/native/components/common/FormField.js
packages/edge-login-ui-rn/src/native/components/common/Modal.js
packages/edge-login-ui-rn/src/native/components/materialWrappers/Input.js
packages/edge-login-ui-rn/src/native/connectors/abSpecific/OtpAuthCodeModalConnector.js
packages/edge-login-ui-rn/src/native/connectors/componentConnectors/OtpBackupKeyConnector.js

task: Automatically capslock text entry for 2FA code account login
2FA - Don't allow user to tap Done until text is entered

Auto Caps Lock input and Done button of Enter Authentication Code Modal of OTP error screen

---

packages/edge-login-ui-web/src/frame/index.js
packages/edge-login-ui-web/src/frame/root-api.js

The Herasoft team ran into a problem sending transactions, and since the web is using an older version of edge-core-js, we need to hack in some kind of solution.

web: Add a temporary `etherscanApiKey` field

---

packages/edge-login-ui-rn/src/components/screens/OtpErrorScreen.js
packages/edge-login-ui-rn/src/util/periodicTask.js

This happens if the component unmounts at just the right time. Solve it by adding a `makePeriodicTask` helper to handle all race conditions in a super-paranoid way.

Fix the infinite login loop race condition

---

packages/edge-login-ui-rn/src/components/screens/OtpErrorScreen.js

The current login server won't produce this situation, but it came up in testing (when we had more bugs), so it seems like we should get this fixed now in case the server ever changes its logic and produces this situation.

rn: Don't show the reset button without a reset token

---

packages/edge-login-ui-rn/src/components/screens/OtpErrorScreen.js

If the background voucher-checking task happens at the same time an OTP backup modal login, it might produce an extra voucher on the server. This will bug the user to approve their own device, which is confusing. So, pause the background voucher-checking task as long as the OTP backup modal is visible.

Prevent redundant vouchers from appearing

---

packages/edge-login-ui-rn/src/components/services/ReduxStore.js

The password recovery screen can encounter network errors while starting up, so we should show those to the user.

Catch errors when launching screens

---

packages/edge-login-ui-rn/src/components/modals/QrCodeModal.js
packages/edge-login-ui-rn/src/components/publicApi/PublicOtpRepairScreen.js
packages/edge-login-ui-rn/src/components/screens/existingAccout/SecurityAlertsScreen.js

The next version of edge-core-js will have breaking changes. We can easily be compatible with both 0.17 and 0.18 by using the more modern API's instead of the old deprecated API's.

rn: Prepare for edge-core-js breaking changes

---

packages/edge-login-ui-rn/src/components/screens/existingAccout/SecurityAlertsScreen.js

- rn: Close the security alerts screen if the list starts empty. There is a race condition that that cause this to happen, so this is a simple stop-gap solution.

rn: Close the security alerts if the list starts empty

---

packages/edge-login-ui-rn/src/components/themed/Fade.js

This fix broken ability of Fade component to hide(remove) children after animation is done and opacity set to zero

Create Account - Confirm & Finish button invisible and able to create an account without the check marks 

---

packages/edge-login-ui-rn/src/actions/CreateAccountActions.js
packages/edge-login-ui-rn/src/components/navigation/Router.js
packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountPinScreen.js
packages/edge-login-ui-rn/src/components/screens/newAccount/NewAccountReviewScreen.js
packages/edge-login-ui-rn/src/components/screens/newAccount/TermsAndConditionsScreen.js

Here I fix two task in one Pr:
1.  Add back button to the TermsAndConditions screen
2.  Сhange the order of screens
If you have made **any** visual changes to the GUI. Make sure you have:

Switch scenes

---

packages/edge-login-ui-rn/src/actions/PasswordRecoveryActions.ts

If the share library throws as "User did not" error, filter that out.

rn: Do not show an error when cancelling sharing

---

packages/edge-login-ui-rn/src/reducers/SceneReducer.ts

During the changes made for the workflow-based scene transition (PRs
caused issues with scene transitions when recovering passwords using
recovery tokens since the completion of that workflow transitions
through the START_RESECURE action type.
This change restores handling for the START_RESECURE action type.

Handle START_RESECURE action type

---

packages/edge-login-ui-rn/src/components/common/Header.tsx
packages/edge-login-ui-rn/src/components/scenes/LandingScene.tsx
packages/edge-login-ui-rn/src/components/scenes/RecoveryLoginScene.tsx

The "Create Account" text issue [issue](https://app.asana.com/0/1200661683177277/1201264647824046) would have actually been fixed by @swansontec's [commit](https://github.com/EdgeApp/edge-login-ui/pull/354/commits/d4d9bf2262025bc1cb6f5ed06aaa8479734d74d3#diff-76595d2394a38476a722585ce22cfdfc7e5fcb06efa2fbd7bce9eb3f4e191314R55) in [this PR](https://github.com/EdgeApp/edge-login-ui/pull/354).
This PR changes a few more instances of `<Button>`'s to `<MainButtons>` in UI2 login scenes. 
Scenes from [existingAccount](https://github.com/EdgeApp/edge-login-ui/tree/master/packages/edge-login-ui-rn/src/components/scenes/existingAccout) with `<Button>` components weren't modified since that UI will eventually be moved to UI2. 
|  ![Simulator Screen Shot - iPhone 13 mini - 2022-05-24 at 09 43 …

Changed Button occurrences to MainButton

---

packages/edge-login-ui-rn/src/components/publicApi/PublicChangeRecoveryScreen.tsx
packages/edge-login-ui-rn/src/components/publicApi/PublicOtpRepairScreen.tsx

'Undefined' was being written in the recovery email because the Branding appName was not being set.
---
- https://app.asana.com/0/0/1202341512055666

Accept Branding in PasswordRecoveryScreen
